### ISSUE TITLE
Неработающий код в 1.5.1

### ISSUE THREAD

**Issue by zlumyo** [igrishaev/clj-book#98]
В предпоследнем примере кода про Middleware, Параметры запроса
```clojure
(require '[ring.middleware.keyword-params :refer [wrap-keyword-params]])
(def app (wrap-keyword-params (wrap-params app-naked)))
```
прокралась ошибка. Всё таки обёртки надо переставить местами. В ходе REPL-cессии заметил, что строковые ключи словаря `:params` так и остаются строками.

**Comment by zlumyo** [comment]
Прошу прощения. Зарепортил сразу, как у видел, а ведь дальше это поясняется.

**Comment by igrishaev** [comment]
Спасибо, что обратили внимание. В исходном варианте я сам напутал, и только потом исправил.
