### ISSUE TITLE
Пример кода не соответствует предваряющим его словам

### ISSUE THREAD

**Issue by zlumyo** [igrishaev/clj-book#99]
https://github.com/igrishaev/clj-book/blob/5f927d71a4e1bcd92c62602306e3e5c5deb99e40/ch2-spec.tex#L431

Пример кода после этого абзаца не показывает применение `:min-count`, хотя, логично предположить, что оно там должно быть.

**Comment by igrishaev** [comment]
Исправил, спасибо.
